export default [
    {
        "abcount": "024048400530100",
        "objectId": "1614219",
        "idFirme": "116977",
        "codeFirme": null,
        "nameFirme": "КП \"КИЇВТЕПЛОЕНЕРГО\"",
        "platCode": null,
        "namePlat": null,
        "fio": "FIO F.I.O.",
        "abcounter": null,
        "uniqId": null,
        "counterNo": null,
        "preValue": "66",
        "oldValue": "66",
        "newValue": "67",
        "newTransmissionTime": "2023-10-09",
        "nameServic": null,
        "abccnt": null,
        "isseveralTarif": null,
        "dateInd": null,
        "zona1": null,
        "zona2": null,
        "zona3": null,
        "serviceType": "1"
    },
    {
        "abcount": "024048400530100",
        "objectId": "1614219",
        "idFirme": "116977",
        "codeFirme": null,
        "nameFirme": "КП \"КИЇВТЕПЛОЕНЕРГО\"",
        "platCode": null,
        "namePlat": null,
        "fio": "FIO F.I.O.",
        "abcounter": null,
        "uniqId": null,
        "counterNo": null,
        "preValue": null,
        "oldValue": null,
        "newValue": "66",
        "newTransmissionTime": "2023-07-27",
        "nameServic": null,
        "abccnt": null,
        "isseveralTarif": null,
        "dateInd": null,
        "zona1": null,
        "zona2": null,
        "zona3": null,
        "serviceType": "1"
    },
    {
        "abcount": "024048400530100",
        "objectId": "1614219",
        "idFirme": "116977",
        "codeFirme": null,
        "nameFirme": "КП \"КИЇВТЕПЛОЕНЕРГО\"",
        "platCode": null,
        "namePlat": null,
        "fio": "FIO F.I.O.",
        "abcounter": null,
        "uniqId": null,
        "counterNo": null,
        "preValue": null,
        "oldValue": null,
        "newValue": "66,01",
        "newTransmissionTime": "2023-07-27",
        "nameServic": null,
        "abccnt": null,
        "isseveralTarif": null,
        "dateInd": null,
        "zona1": null,
        "zona2": null,
        "zona3": null,
        "serviceType": "1"
    },
    {
        "abcount": "024048400530100",
        "objectId": "1614219",
        "idFirme": "116977",
        "codeFirme": null,
        "nameFirme": "КП \"КИЇВТЕПЛОЕНЕРГО\"",
        "platCode": null,
        "namePlat": null,
        "fio": "FIO F.I.O.",
        "abcounter": null,
        "uniqId": null,
        "counterNo": null,
        "preValue": null,
        "oldValue": null,
        "newValue": "48",
        "newTransmissionTime": "2023-02-22",
        "nameServic": null,
        "abccnt": null,
        "isseveralTarif": null,
        "dateInd": null,
        "zona1": null,
        "zona2": null,
        "zona3": null,
        "serviceType": "1"
    },
    {
        "abcount": "024048400530100",
        "objectId": "1614219",
        "idFirme": "116977",
        "codeFirme": null,
        "nameFirme": "КП \"КИЇВТЕПЛОЕНЕРГО\"",
        "platCode": null,
        "namePlat": null,
        "fio": "FIO F.I.O.",
        "abcounter": null,
        "uniqId": null,
        "counterNo": null,
        "preValue": null,
        "oldValue": null,
        "newValue": "48",
        "newTransmissionTime": "2023-02-22",
        "nameServic": null,
        "abccnt": null,
        "isseveralTarif": null,
        "dateInd": null,
        "zona1": null,
        "zona2": null,
        "zona3": null,
        "serviceType": "1"
    },
    {
        "abcount": "15019805324",
        "objectId": "1614219",
        "idFirme": "121722",
        "codeFirme": null,
        "nameFirme": "ТОВ \"КИЇВСЬКІ ЕНЕРГЕТИЧНІ ПОСЛУГИ\"",
        "platCode": null,
        "namePlat": null,
        "fio": "FIO F.I.O.",
        "abcounter": null,
        "uniqId": null,
        "counterNo": null,
        "preValue": null,
        "oldValue": null,
        "newValue": "0",
        "newTransmissionTime": "2023-02-22",
        "nameServic": null,
        "abccnt": null,
        "isseveralTarif": null,
        "dateInd": null,
        "zona1": null,
        "zona2": null,
        "zona3": null,
        "serviceType": "2"
    },
    {
        "abcount": "15019805324",
        "objectId": "1614219",
        "idFirme": "121722",
        "codeFirme": null,
        "nameFirme": "ТОВ \"КИЇВСЬКІ ЕНЕРГЕТИЧНІ ПОСЛУГИ\"",
        "platCode": null,
        "namePlat": null,
        "fio": "FIO F.I.O.",
        "abcounter": null,
        "uniqId": null,
        "counterNo": null,
        "preValue": null,
        "oldValue": null,
        "newValue": "0",
        "newTransmissionTime": "2023-02-22",
        "nameServic": null,
        "abccnt": null,
        "isseveralTarif": null,
        "dateInd": null,
        "zona1": null,
        "zona2": null,
        "zona3": null,
        "serviceType": "2"
    },
    {
        "abcount": "673",
        "objectId": "1614219",
        "idFirme": "114161",
        "codeFirme": null,
        "nameFirme": "ПрАТ \"АК \"Київводоканал\"",
        "platCode": null,
        "namePlat": null,
        "fio": "FIO F.I.O.",
        "abcounter": null,
        "uniqId": null,
        "counterNo": null,
        "preValue": null,
        "oldValue": null,
        "newValue": "97",
        "newTransmissionTime": "2023-02-22",
        "nameServic": null,
        "abccnt": null,
        "isseveralTarif": null,
        "dateInd": null,
        "zona1": null,
        "zona2": null,
        "zona3": null,
        "serviceType": "4"
    },
    {
        "abcount": "024048400530100",
        "objectId": "1614219",
        "idFirme": "116977",
        "codeFirme": null,
        "nameFirme": "КП \"КИЇВТЕПЛОЕНЕРГО\"",
        "platCode": null,
        "namePlat": null,
        "fio": "FIO F.I.O.",
        "abcounter": null,
        "uniqId": null,
        "counterNo": null,
        "preValue": null,
        "oldValue": null,
        "newValue": "48",
        "newTransmissionTime": "2023-02-26",
        "nameServic": null,
        "abccnt": null,
        "isseveralTarif": null,
        "dateInd": null,
        "zona1": null,
        "zona2": null,
        "zona3": null,
        "serviceType": "1"
    },
    {
        "abcount": "024048400530100",
        "objectId": "1614219",
        "idFirme": "116977",
        "codeFirme": null,
        "nameFirme": "КП \"КИЇВТЕПЛОЕНЕРГО\"",
        "platCode": null,
        "namePlat": null,
        "fio": "FIO F.I.O.",
        "abcounter": null,
        "uniqId": null,
        "counterNo": null,
        "preValue": null,
        "oldValue": null,
        "newValue": "47,2",
        "newTransmissionTime": "2023-04-06",
        "nameServic": null,
        "abccnt": null,
        "isseveralTarif": null,
        "dateInd": null,
        "zona1": null,
        "zona2": null,
        "zona3": null,
        "serviceType": "1"
    },
    {
        "abcount": "024048400530100",
        "objectId": "1614219",
        "idFirme": "116977",
        "codeFirme": null,
        "nameFirme": "КП \"КИЇВТЕПЛОЕНЕРГО\"",
        "platCode": null,
        "namePlat": null,
        "fio": "FIO F.I.O.",
        "abcounter": null,
        "uniqId": null,
        "counterNo": null,
        "preValue": null,
        "oldValue": null,
        "newValue": "54,2",
        "newTransmissionTime": "2023-04-06",
        "nameServic": null,
        "abccnt": null,
        "isseveralTarif": null,
        "dateInd": null,
        "zona1": null,
        "zona2": null,
        "zona3": null,
        "serviceType": "1"
    },
    {
        "abcount": "024048400530100",
        "objectId": "1614219",
        "idFirme": "116977",
        "codeFirme": null,
        "nameFirme": "КП \"КИЇВТЕПЛОЕНЕРГО\"",
        "platCode": null,
        "namePlat": null,
        "fio": "FIO F.I.O.",
        "abcounter": null,
        "uniqId": null,
        "counterNo": null,
        "preValue": null,
        "oldValue": null,
        "newValue": "54,2",
        "newTransmissionTime": "2023-04-06",
        "nameServic": null,
        "abccnt": null,
        "isseveralTarif": null,
        "dateInd": null,
        "zona1": null,
        "zona2": null,
        "zona3": null,
        "serviceType": "1"
    },
    {
        "abcount": "024048400530100",
        "objectId": "1614219",
        "idFirme": "116977",
        "codeFirme": null,
        "nameFirme": "КП \"КИЇВТЕПЛОЕНЕРГО\"",
        "platCode": null,
        "namePlat": null,
        "fio": "FIO F.I.O.",
        "abcounter": null,
        "uniqId": null,
        "counterNo": null,
        "preValue": null,
        "oldValue": null,
        "newValue": "54.1",
        "newTransmissionTime": "2023-04-06",
        "nameServic": null,
        "abccnt": null,
        "isseveralTarif": null,
        "dateInd": null,
        "zona1": null,
        "zona2": null,
        "zona3": null,
        "serviceType": "1"
    },
    {
        "abcount": "024048400530100",
        "objectId": "1614219",
        "idFirme": "116977",
        "codeFirme": null,
        "nameFirme": "КП \"КИЇВТЕПЛОЕНЕРГО\"",
        "platCode": null,
        "namePlat": null,
        "fio": "FIO F.I.O.",
        "abcounter": null,
        "uniqId": null,
        "counterNo": null,
        "preValue": null,
        "oldValue": null,
        "newValue": "108",
        "newTransmissionTime": "2023-04-06",
        "nameServic": null,
        "abccnt": null,
        "isseveralTarif": null,
        "dateInd": null,
        "zona1": null,
        "zona2": null,
        "zona3": null,
        "serviceType": "1"
    },
    {
        "abcount": "024048400530100",
        "objectId": "1614219",
        "idFirme": "116977",
        "codeFirme": null,
        "nameFirme": "КП \"КИЇВТЕПЛОЕНЕРГО\"",
        "platCode": null,
        "namePlat": null,
        "fio": "FIO F.I.O.",
        "abcounter": null,
        "uniqId": null,
        "counterNo": null,
        "preValue": null,
        "oldValue": null,
        "newValue": "52",
        "newTransmissionTime": "2023-04-06",
        "nameServic": null,
        "abccnt": null,
        "isseveralTarif": null,
        "dateInd": null,
        "zona1": null,
        "zona2": null,
        "zona3": null,
        "serviceType": "1"
    },
    {
        "abcount": "024048400530100",
        "objectId": "1614219",
        "idFirme": "116977",
        "codeFirme": null,
        "nameFirme": "КП \"КИЇВТЕПЛОЕНЕРГО\"",
        "platCode": null,
        "namePlat": null,
        "fio": "FIO F.I.O.",
        "abcounter": null,
        "uniqId": null,
        "counterNo": null,
        "preValue": null,
        "oldValue": null,
        "newValue": "55",
        "newTransmissionTime": "2023-04-06",
        "nameServic": null,
        "abccnt": null,
        "isseveralTarif": null,
        "dateInd": null,
        "zona1": null,
        "zona2": null,
        "zona3": null,
        "serviceType": "1"
    },
    {
        "abcount": "024048400530100",
        "objectId": "1614219",
        "idFirme": "116977",
        "codeFirme": null,
        "nameFirme": "КП \"КИЇВТЕПЛОЕНЕРГО\"",
        "platCode": null,
        "namePlat": null,
        "fio": "FIO F.I.O.",
        "abcounter": null,
        "uniqId": null,
        "counterNo": null,
        "preValue": null,
        "oldValue": null,
        "newValue": "64",
        "newTransmissionTime": "2023-06-28",
        "nameServic": null,
        "abccnt": null,
        "isseveralTarif": null,
        "dateInd": null,
        "zona1": null,
        "zona2": null,
        "zona3": null,
        "serviceType": "1"
    },
    {
        "abcount": "673",
        "objectId": "1614219",
        "idFirme": "114161",
        "codeFirme": null,
        "nameFirme": "ПрАТ \"АК \"Київводоканал\"",
        "platCode": null,
        "namePlat": null,
        "fio": "FIO F.I.O.",
        "abcounter": null,
        "uniqId": null,
        "counterNo": null,
        "preValue": null,
        "oldValue": null,
        "newValue": "126",
        "newTransmissionTime": "2023-06-28",
        "nameServic": null,
        "abccnt": null,
        "isseveralTarif": null,
        "dateInd": null,
        "zona1": null,
        "zona2": null,
        "zona3": null,
        "serviceType": "4"
    },
    {
        "abcount": "024048400530100",
        "objectId": "1614219",
        "idFirme": "116977",
        "codeFirme": null,
        "nameFirme": "КП \"КИЇВТЕПЛОЕНЕРГО\"",
        "platCode": null,
        "namePlat": null,
        "fio": "FIO F.I.O.",
        "abcounter": null,
        "uniqId": null,
        "counterNo": null,
        "preValue": "66",
        "oldValue": "66",
        "newValue": "67",
        "newTransmissionTime": "2023-10-09",
        "nameServic": null,
        "abccnt": null,
        "isseveralTarif": null,
        "dateInd": null,
        "zona1": null,
        "zona2": null,
        "zona3": null,
        "serviceType": "1"
    },
    {
        "abcount": "673",
        "objectId": "1614219",
        "idFirme": "114161",
        "codeFirme": null,
        "nameFirme": "ПрАТ \"АК \"Київводоканал\"",
        "platCode": null,
        "namePlat": null,
        "fio": "FIO F.I.O.",
        "abcounter": null,
        "uniqId": null,
        "counterNo": null,
        "preValue": "133",
        "oldValue": "144",
        "newValue": "145",
        "newTransmissionTime": "2023-10-09",
        "nameServic": null,
        "abccnt": null,
        "isseveralTarif": null,
        "dateInd": null,
        "zona1": null,
        "zona2": null,
        "zona3": null,
        "serviceType": "4"
    },
    {
        "abcount": "673",
        "objectId": "1614219",
        "idFirme": "114161",
        "codeFirme": null,
        "nameFirme": "ПрАТ \"АК \"Київводоканал\"",
        "platCode": null,
        "namePlat": null,
        "fio": "FIO F.I.O.",
        "abcounter": null,
        "uniqId": null,
        "counterNo": null,
        "preValue": "66",
        "oldValue": "66",
        "newValue": "67",
        "newTransmissionTime": "2023-10-09",
        "nameServic": null,
        "abccnt": null,
        "isseveralTarif": null,
        "dateInd": null,
        "zona1": null,
        "zona2": null,
        "zona3": null,
        "serviceType": "4"
    },
    {
        "abcount": "024048400530100",
        "objectId": "1614219",
        "idFirme": "116977",
        "codeFirme": null,
        "nameFirme": "КП \"КИЇВТЕПЛОЕНЕРГО\"",
        "platCode": null,
        "namePlat": null,
        "fio": "FIO F.I.O.",
        "abcounter": null,
        "uniqId": null,
        "counterNo": null,
        "preValue": "66",
        "oldValue": "66",
        "newValue": "67",
        "newTransmissionTime": "2023-10-09",
        "nameServic": null,
        "abccnt": null,
        "isseveralTarif": null,
        "dateInd": null,
        "zona1": null,
        "zona2": null,
        "zona3": null,
        "serviceType": "1"
    },
    {
        "abcount": "673",
        "objectId": "1614219",
        "idFirme": "114161",
        "codeFirme": null,
        "nameFirme": "ПрАТ \"АК \"Київводоканал\"",
        "platCode": null,
        "namePlat": null,
        "fio": "FIO F.I.O.",
        "abcounter": null,
        "uniqId": null,
        "counterNo": null,
        "preValue": "133",
        "oldValue": "144",
        "newValue": "145",
        "newTransmissionTime": "2023-10-09",
        "nameServic": null,
        "abccnt": null,
        "isseveralTarif": null,
        "dateInd": null,
        "zona1": null,
        "zona2": null,
        "zona3": null,
        "serviceType": "4"
    },
    {
        "abcount": "673",
        "objectId": "1614219",
        "idFirme": "114161",
        "codeFirme": null,
        "nameFirme": "ПрАТ \"АК \"Київводоканал\"",
        "platCode": null,
        "namePlat": null,
        "fio": "FIO F.I.O.",
        "abcounter": null,
        "uniqId": null,
        "counterNo": null,
        "preValue": "66",
        "oldValue": "66",
        "newValue": "67",
        "newTransmissionTime": "2023-10-09",
        "nameServic": null,
        "abccnt": null,
        "isseveralTarif": null,
        "dateInd": null,
        "zona1": null,
        "zona2": null,
        "zona3": null,
        "serviceType": "4"
    },
    {
        "abcount": "024048400530100",
        "objectId": "1614219",
        "idFirme": "116977",
        "codeFirme": null,
        "nameFirme": "КП \"КИЇВТЕПЛОЕНЕРГО\"",
        "platCode": null,
        "namePlat": null,
        "fio": "FIO F.I.O.",
        "abcounter": null,
        "uniqId": null,
        "counterNo": null,
        "preValue": "66",
        "oldValue": "66",
        "newValue": "67",
        "newTransmissionTime": "2023-10-09",
        "nameServic": null,
        "abccnt": null,
        "isseveralTarif": null,
        "dateInd": null,
        "zona1": null,
        "zona2": null,
        "zona3": null,
        "serviceType": "1"
    },
    {
        "abcount": "673",
        "objectId": "1614219",
        "idFirme": "114161",
        "codeFirme": null,
        "nameFirme": "ПрАТ \"АК \"Київводоканал\"",
        "platCode": null,
        "namePlat": null,
        "fio": "FIO F.I.O.",
        "abcounter": null,
        "uniqId": null,
        "counterNo": null,
        "preValue": "133",
        "oldValue": "144",
        "newValue": "145",
        "newTransmissionTime": "2023-10-09",
        "nameServic": null,
        "abccnt": null,
        "isseveralTarif": null,
        "dateInd": null,
        "zona1": null,
        "zona2": null,
        "zona3": null,
        "serviceType": "4"
    },
    {
        "abcount": "673",
        "objectId": "1614219",
        "idFirme": "114161",
        "codeFirme": null,
        "nameFirme": "ПрАТ \"АК \"Київводоканал\"",
        "platCode": null,
        "namePlat": null,
        "fio": "FIO F.I.O.",
        "abcounter": null,
        "uniqId": null,
        "counterNo": null,
        "preValue": "66",
        "oldValue": "66",
        "newValue": "67",
        "newTransmissionTime": "2023-10-09",
        "nameServic": null,
        "abccnt": null,
        "isseveralTarif": null,
        "dateInd": null,
        "zona1": null,
        "zona2": null,
        "zona3": null,
        "serviceType": "4"
    },
    {
        "abcount": "024048400530100",
        "objectId": "1614219",
        "idFirme": "116977",
        "codeFirme": null,
        "nameFirme": "КП \"КИЇВТЕПЛОЕНЕРГО\"",
        "platCode": null,
        "namePlat": null,
        "fio": "FIO F.I.O.",
        "abcounter": null,
        "uniqId": null,
        "counterNo": null,
        "preValue": "66",
        "oldValue": "66",
        "newValue": "67",
        "newTransmissionTime": "2023-10-09",
        "nameServic": null,
        "abccnt": null,
        "isseveralTarif": null,
        "dateInd": null,
        "zona1": null,
        "zona2": null,
        "zona3": null,
        "serviceType": "1"
    },
    {
        "abcount": "673",
        "objectId": "1614219",
        "idFirme": "114161",
        "codeFirme": null,
        "nameFirme": "ПрАТ \"АК \"Київводоканал\"",
        "platCode": null,
        "namePlat": null,
        "fio": "FIO F.I.O.",
        "abcounter": null,
        "uniqId": null,
        "counterNo": null,
        "preValue": "133",
        "oldValue": "144",
        "newValue": "145",
        "newTransmissionTime": "2023-10-09",
        "nameServic": null,
        "abccnt": null,
        "isseveralTarif": null,
        "dateInd": null,
        "zona1": null,
        "zona2": null,
        "zona3": null,
        "serviceType": "4"
    },
    {
        "abcount": "673",
        "objectId": "1614219",
        "idFirme": "114161",
        "codeFirme": null,
        "nameFirme": "ПрАТ \"АК \"Київводоканал\"",
        "platCode": null,
        "namePlat": null,
        "fio": "FIO F.I.O.",
        "abcounter": null,
        "uniqId": null,
        "counterNo": null,
        "preValue": "66",
        "oldValue": "66",
        "newValue": "67",
        "newTransmissionTime": "2023-10-09",
        "nameServic": null,
        "abccnt": null,
        "isseveralTarif": null,
        "dateInd": null,
        "zona1": null,
        "zona2": null,
        "zona3": null,
        "serviceType": "4"
    },
    {
        "abcount": "673",
        "objectId": "1614219",
        "idFirme": "114161",
        "codeFirme": null,
        "nameFirme": "ПрАТ \"АК \"Київводоканал\"",
        "platCode": null,
        "namePlat": null,
        "fio": "FIO F.I.O.",
        "abcounter": null,
        "uniqId": null,
        "counterNo": null,
        "preValue": null,
        "oldValue": null,
        "newValue": "63",
        "newTransmissionTime": "2023-06-27",
        "nameServic": null,
        "abccnt": null,
        "isseveralTarif": null,
        "dateInd": null,
        "zona1": null,
        "zona2": null,
        "zona3": null,
        "serviceType": "4"
    },
    {
        "abcount": "024048400530100",
        "objectId": "1614219",
        "idFirme": "116977",
        "codeFirme": null,
        "nameFirme": "КП \"КИЇВТЕПЛОЕНЕРГО\"",
        "platCode": null,
        "namePlat": null,
        "fio": "FIO F.I.O.",
        "abcounter": null,
        "uniqId": null,
        "counterNo": null,
        "preValue": "62",
        "oldValue": "64.0",
        "newValue": "65",
        "newTransmissionTime": "2023-07-25",
        "nameServic": null,
        "abccnt": null,
        "isseveralTarif": null,
        "dateInd": null,
        "zona1": null,
        "zona2": null,
        "zona3": null,
        "serviceType": "1"
    },
    {
        "abcount": "673",
        "objectId": "1614219",
        "idFirme": "114161",
        "codeFirme": null,
        "nameFirme": "ПрАТ \"АК \"Київводоканал\"",
        "platCode": null,
        "namePlat": null,
        "fio": "FIO F.I.O.",
        "abcounter": null,
        "uniqId": null,
        "counterNo": null,
        "preValue": "62",
        "oldValue": "63",
        "newValue": "65",
        "newTransmissionTime": "2023-07-25",
        "nameServic": null,
        "abccnt": null,
        "isseveralTarif": null,
        "dateInd": null,
        "zona1": null,
        "zona2": null,
        "zona3": null,
        "serviceType": "4"
    },
    {
        "abcount": "673",
        "objectId": "1614219",
        "idFirme": "114161",
        "codeFirme": null,
        "nameFirme": "ПрАТ \"АК \"Київводоканал\"",
        "platCode": null,
        "namePlat": null,
        "fio": "FIO F.I.O.",
        "abcounter": null,
        "uniqId": null,
        "counterNo": null,
        "preValue": "119",
        "oldValue": "126",
        "newValue": "127",
        "newTransmissionTime": "2023-07-25",
        "nameServic": null,
        "abccnt": null,
        "isseveralTarif": null,
        "dateInd": null,
        "zona1": null,
        "zona2": null,
        "zona3": null,
        "serviceType": "4"
    },
    {
        "abcount": "024048400530100",
        "objectId": "1614219",
        "idFirme": "116977",
        "codeFirme": "1416",
        "nameFirme": "КПВОК \"КИЇВТЕПЛОЕНЕРГО\"",
        "platCode": "024048400530100",
        "namePlat": "ПОСТАЧАННЯ ГАРЯЧОЇ ВОДИ - ГВ(ГВП) ЛІЧИЛЬНИК",
        "fio": "СКАЗАТНЯ Л. В.",
        "abcounter": "2021 05010121",
        "uniqId": "1530893",
        "counterNo": "1",
        "preValue": "44",
        "oldValue": "51",
        "newValue": "51.1",
        "newTransmissionTime": "2023-03-01T08:14:41Z",
        "nameServic": "ПГВ",
        "abccnt": "Ліч1",
        "isseveralTarif": "0",
        "dateInd": null,
        "zona1": null,
        "zona2": null,
        "zona3": null,
        "serviceType": "1"
    }
];
